### ISSUE TITLE
bug: the emoji cap is 101, not 100

### ISSUE THREAD

**Issue by infi** [revoltchat/backend#197] opened 2022-08-30 19:23 UTC
### What happened?

as this is a very unintuitive number, i assume this is the wrong comparison operator being used [at this line](https://github.com/revoltchat/backend/blob/master/crates/delta/src/routes/customisation/emoji_create.rs#L58)

**Comment by VeiledProduct80** [comment] 2022-08-30 19:24
Literally cope it should be 101

**Comment by vrvray** [comment] 2022-08-30 19:28
i think it really isn't an issue, probably would be enough in notifying what the limit is in the first place

**Comment by DeMoN100** [comment] 2022-08-30 19:39
It's not a bug. I am the one who first mentioned it in the first place as I tested in one server I made. You can upload 101 emojis you can join the server and see yourself this is not a counting error.

**Comment by Rexogamer** [comment] 2022-08-30 19:40
This *is* unintentional and unintuitive behaviour

**Comment by insertish** [comment] 2022-09-01 08:03
Closed in #198

It's an arbitrary amount anyways (so it may be increased in the future, but I mean one slot isn't going to make that much of a difference here anyways), in any case, it should be a nice rounded number or it's going to drive me insane.

**Closed by insertish** 2022-09-01 08:03 UTC
Labels: bug
